Repository chalstead16/trivia-night, pull requests merged in 2022-04, with the labels that each got.

#16 Interface refactor
  src/components/App/App.tsx
  src/components/QuestionCard/QuestionCard.tsx
  src/components/Questions/Questions.tsx
Labels: Refactor

#18 Categories/gj
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Categories/Categories.tsx
Labels: enhancement, Refactor

#24 Refactor game/ch
  src/components/App/App.tsx
  src/components/Game/Game.tsx
  src/components/GameQuestionCard/GameQuestionCard.tsx
  src/components/QuestionCard/QuestionCard.tsx
  src/components/Questions/Questions.tsx
Labels: bug, enhancement

#26 Cypress testing/gj
  cypress.json
  cypress/fixtures/questions.json
  cypress/integration/Game_spec.ts
  cypress/integration/MainPage_spec.ts
  cypress/integration/Questions_spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/components/Categories/Categories.tsx
Labels: documentation, Refactor

#28 Refactor typescript/ch
  src/components/App/App.tsx
  src/components/Categories/Categories.tsx
  src/components/Difficulty/Difficulty.css
  src/components/Difficulty/Difficulty.tsx
  src/components/Game/Game.tsx
  src/components/GameQuestionCard/GameQuestionCard.tsx
  src/components/Header/Header.tsx
  src/components/QuestionCard/QuestionCard.tsx
  src/components/Questions/Questions.tsx
  src/utilities/utilities.tsx
Labels: Refactor

#31 Readme/sm
  README.md
Labels: Refactor
